name: Terraform plan
on:
  push:
    branches:
      - main
  workflow_dispatch:   

jobs:
      Terraform_plan:
        uses: "mahadikbs/reusable-workflows/.github/workflows/terrafom-plan.yaml@main"
        with:
          environment: prod
          runner: ubuntu-latest
        secrets:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}