name: Terraform destroy
on:
  workflow_dispatch:   

jobs:
      Terraform_destroy:
        uses: mahadikbs/reusable-workflows/.github/workflows/terraform-destroy.yaml@main
        with:
          environment: prod
          runner: ubuntu-latest
        secrets:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}