name: Terraform plan
on:
  push:
    branches:
      - main
  workflow_dispatch:   

jobs:
      Terraform_plan:
        uses: mahadikbs/reusable-workflows/.github/workflows/terraform-plan.yaml@main
        with:
          environment: prod
          runner: ubuntu-latest
        secrets:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}